name: livwell
description: "A Social Welfare Application"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0-209.1.beta

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.12.1
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.4.4
  firebase_messaging: ^15.2.4
  firebase_auth: ^5.5.1
  firebase_app_check: ^0.3.2+4
  firebase_remote_config: ^5.4.2

  flutter_otp_text_field: ^1.1.3+2
  flutter_svg: ^2.0.10+1
  flutter_native_splash: ^2.4.1 
  flutter_holo_date_picker: ^2.0.0

  in_app_update: ^4.2.3
  image_picker: ^1.1.2
  intl: ^0.19.0
  form_validator: ^2.1.1
  get: ^4.6.6
  url_launcher: ^6.3.0
  path_provider: ^2.1.3
  pinput: ^5.0.0
  smart_auth: ^3.2.0
  cached_network_image: ^3.3.1
  awesome_snackbar_content: ^0.1.3
  permission_handler: ^11.3.1
  shimmer: ^3.0.0
  http: ^1.2.2
  equatable: ^2.0.5
  share_plus: ^10.0.0
  sign_in_with_apple: ^6.1.4
  google_sign_in: ^6.3.0
  hive: ^2.2.3
  uuid: ^4.5.1
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: ^2.0.1
  build_runner: ^2.4.11
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/logo/
    - assets/icons/
    - assets/icon/
    - assets/svgs/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100


flutter_launcher_icons:
  android: true
  image_path: "assets/logo/livwell_logo.png"
  android_name: "ic_launcher"
  ios_name: "AppIcon"

flutter_native_splash:
  android: true
  ios: true
  web: false

  color: "#ffffff" 
  color_dark: "#252525"  

  image: assets/logo/livwell_logo.png
  image_dark: assets/logo/livwell_logo.png

  android_12:
    color: "#ffffff" 
    color_dark: "#252525"      

    image: assets/logo/livwell_logo.png 
    image_dark: assets/logo/livwell_logo.png